- project:
    check:
      queue: thoth-station/core
      jobs:
        - linters
    gate:
      queue: thoth-station/core
      jobs:
        - linters
    post:
      jobs:
        - trigger-build:
            vars:
              webhook_url: "https://paas.upshift.redhat.com/oapi/v1/namespaces/thoth-test-core/buildconfigs/package-releases-job/webhooks/"
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - linters
