apiVersion: v1
kind: Template
labels:
  template: thoth-package-releases-buildconfig
  thoth: 0.1.0
metadata:
  name: thoth-package-releases-buildconfig
  annotations:
    description: This is Thoth Core - Package Releases Job BuildConfig
    openshift.io/display-name: "Thoth: Package Releases Job BuildConfig"
    version: 0.1.1
    tags: poc,thoth,ai-stacks,package-releases
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Package Releases Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: package-releases
    labels:
      app: thoth-core
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: "package-releases-job:${IMAGE_STREAM_TAG}"
    source:
      type: Git
      git:
        uri: ${GITHUB_URL}
        ref: ${GITHUB_REF}
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: python-36-centos7:latest
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChange: {}

parameters:
- description: Name of the github repository for Thoth's Package Releases Job
  displayName: Git Repository
  required: true
  name: GITHUB_URL
  value: 'https://github.com/thoth-station/package-releases-job'

- description: Git reference to be used for Thoth's Package Releases Job
  displayName: Git Reference
  required: true
  name: GITHUB_REF
  value: 'master'

- description: Tag of the output ImageStream the resulting container image should go to
  displayName: ImageStream Tag
  required: true
  name: IMAGE_STREAM_TAG
  value: 'latest'