apiVersion: v1
kind: Template
metadata:
  name: package-releases-cronjob
  annotations:
    description: "Thoth: Package Releases Job"
    openshift.io/display-name: "Thoth: Package Releases Job"
    version: 0.4.0
    tags: thoth,ai-stacks,aistacks,package-releases
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Package
      Releases Job to OpenShift.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: package-releases-cronjob
    app: thoth
    component: package-releases

parameters:
  - displayName: Suspend CronJob run
    description: Suspend CronJob run
    required: true
    name: THOTH_SUSPEND_JOB
    value: "true"

  - description: Project the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    # TODO adjust ansible role so that we dont need a default here
    value: "thoth-infra-stage"

  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - kind: CronJob
    apiVersion: batch/v1beta1
    metadata:
      name: package-releases
      labels:
        app: thoth
        component: package-releases
    spec:
      schedule: "@daily"
      suspend: ${{THOTH_SUSPEND_JOB}}
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 2
      startingDeadlineSeconds: 99
      failedJobsHistoryLimit: 4
      jobTemplate:
        spec:
          template:
            metadata:
              labels:
                app: thoth
                component: package-releases
            spec:
              containers:
                - image: "${IMAGE_STREAM_NAMESPACE}/package-releases-job:${IMAGE_STREAM_TAG}"
                  name: package-releases
                  env:
                    - name: THOTH_PACKAGE_RELEASES_ONLY_IF_PACKAGE_SEEN
                      valueFrom:
                        configMapKeyRef:
                          key: package-releases-only-if-package-seen
                          name: thoth
                    - name: RSYSLOG_HOST
                      valueFrom:
                        configMapKeyRef:
                          key: rsyslog-host
                          name: thoth
                    - name: RSYSLOG_PORT
                      valueFrom:
                        configMapKeyRef:
                          key: rsyslog-port
                          name: thoth
                    - name: PROMETHEUS_PUSHGATEWAY_URL
                      valueFrom:
                        configMapKeyRef:
                          name: thoth
                          key: metrics-pushgateway-url
                    - name: SENTRY_DSN
                      valueFrom:
                        secretKeyRef:
                          name: thoth
                          key: sentry-dsn
                    - name: GRAPH_SERVICE_HOST
                      valueFrom:
                        configMapKeyRef:
                          key: graph-service-host
                          name: thoth
                    - name: GRAPH_TLS_PATH
                      value: "/var/run/secrets/dgraph"
                  volumeMounts:
                    - mountPath: /var/run/secrets/dgraph
                      name: dgraph-tls-secrets
                      readOnly: true
                  resources:
                    requests:
                      memory: "256Mi"
                      cpu: "500m"
                    limits:
                      memory: "512Mi"
                      cpu: "500m"
              restartPolicy: OnFailure
              volumes:
                - name: dgraph-tls-secrets
                  secret:
                    defaultMode: 420
                    secretName: dgraph-tls
