apiVersion: v1
kind: Template
labels:
  template: thoth-core
  thoth: 0.1.0
metadata:
  name: thoth-core
  annotations:
    description: This is Thoth Core - Package Releases Job
    openshift.io/display-name: "Thoth: Package Releases Job"
    version: 0.1.0
    tags: poc,thoth,ai-stacks,package_releases
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Thoth Package Releases Job as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
- kind: CronJob
  apiVersion: batch/v2alpha1
  metadata:
    name: package-releases
    namespace: ${THOTH_BACKEND_NAMESPACE}
    labels:
      app: thoth-core
  spec:
    schedule: '*/6 * * * *'
    suspend: true
    concurrencyPolicy: Forbid
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 4
    jobTemplate:
      spec:
        template:
          spec:
            containers:
            - image: package-releases-job
              name: package-releases
              env:
              - name: THOTH_JANUSGRAPH_HOST
                value: 'janusgraph'
              - name: THOTH_JANUSGRAPH_PORT
                value: '80'
              - name: THOTH_PACKAGE_RELEASES_ONLY_IF_PACKAGE_SEEN
                valueFrom:
                  configMapKeyRef:
                    key: package-releases-only-if-package-seen
                    name: thoth                   
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "250m"
            restartPolicy: OnFailure

- kind: ImageStream
  apiVersion: v1
  metadata:
    labels:
      app: thoth-core
    name: package-releases-job
    namespace: ${THOTH_BACKEND_NAMESPACE}
  spec:
    name: latest
    lookupPolicy:
      local: true    

parameters:
- description: Name of the Thoth Backend Namespace
  displayName: Thoth Backend Namespace
  required: true
  name: THOTH_BACKEND_NAMESPACE